### PR TITLE
Modify cmake file to allow builds fully hosted in Xcode with tests ru…

### PR DESCRIPTION
**Pull request by meshula**
…nnable. Update __Bool to bool to be compatible with more std implementations

### CODE REVIEW

**Comment by meshula** [comment]
Please feel free to discuss before merging if anything looks suspicious to you!!

**Comment by KarthikRIyer** [comment]
I'll pull this and see if it builds on Ubuntu today. Sorry for the late reply. I didn't get a notification about the PR in my email.

I haven't taken a detailed look...but why did you change it to a static lib instead of shared?

**Comment by meshula** [comment]
That should be approached differently, via a cmake option. Dylibs can be a bit of a pain under recent macOS versions.

**Comment by KarthikRIyer** [comment]
@meshula the `openTimeTests.cpp` file needs to be renamed to `OpenTimeTests.cpp`.

Is there a specific reason for making the c-bindings a part of the main project? I had used the C++ core as a dependency for the C-bindings because it would have been easier to deal with when we separate the bindings into a different repository.

How can I run the C-bindings tests with the current config?

I tried running the simple `make test` command. That started the python tests. They failed.

Here are the errors:

```console
Python 3.6.9
Running Core tests...
/home/karthik/venv3/lib/python3.6/site-packages/opentimelineio/plugins/manifest.py:33: UserWarning: Module opentimelineio was already imported from /home/karthik/venv3/lib/python3.6/site-packages/opentimelineio/__init__.py, but /home/karthik/meshula/OpenTimelineIO is being added to sys.path
  import pkg_resources
...................................................................................................EFFE.....E.FFF.E.E............................................................................................................................................................................................................./home/karthik/venv3/lib/python3.6/site-packages/opentimelineio/adapters/adapter.py:298: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  args = inspect.getargspec(fn)
..................................
======================================================================
ERROR: test_basic (test_console.CreateShelloutTest.<locals>.newSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 135, in test_basic
    self.run_test()
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 108, in run_test
    raise SystemExit()
SystemExit

======================================================================
ERROR: test_no_media_linker (test_console.CreateShelloutTest.<locals>.newSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 140, in test_no_media_linker
    self.run_test()
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 108, in run_test
    raise SystemExit()
SystemExit

======================================================================
ERROR: test_basic (test_console.CreateShelloutTest.<locals>.newSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 188, in test_basic
    self.run_test()
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 108, in run_test
    raise SystemExit()
SystemExit

======================================================================
ERROR: test_basic (test_console.CreateShelloutTest.<locals>.newSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 123, in test_basic
    self.run_test()
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 108, in run_test
    raise SystemExit()
SystemExit

======================================================================
ERROR: test_basic (test_console.CreateShelloutTest.<locals>.newSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 123, in test_basic
    self.run_test()
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 108, in run_test
    raise SystemExit()
SystemExit

======================================================================
FAIL: test_input_argument_error (test_console.CreateShelloutTest.<locals>.newSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 154, in test_input_argument_error
    self.assertIn('error: adapter', sys.stderr.getvalue())
AssertionError: 'error: adapter' not found in 'Traceback (most recent call last):\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master\n    ws.require(__requires__)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require\n    needed = self.resolve(parse_requirements(requirements))\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve\n    raise VersionConflict(dist, req).with_context(dependent_req)\npkg_resources.ContextualVersionConflict: (pyaaf2 1.4.0 (/home/karthik/venv3/lib/python3.6/site-packages), Requirement.parse(\'pyaaf2==1.2.0\'), {\'OpenTimelineIO\'})\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/karthik/venv3/bin/otiocat", line 6, in <module>\n    from pkg_resources import load_entry_point\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>\n    @_call_aside\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside\n    f(*args, **kwargs)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master\n    return cls._build_from_requirements(__requires__)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements\n    dists = ws.resolve(reqs, Environment())\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound: The \'pyaaf2==1.2.0\' distribution was not found and is required by OpenTimelineIO\n'

======================================================================
FAIL: test_media_linker_argument_error (test_console.CreateShelloutTest.<locals>.newSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 167, in test_media_linker_argument_error
    self.assertIn('error: media linker', sys.stderr.getvalue())
AssertionError: 'error: media linker' not found in 'Traceback (most recent call last):\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master\n    ws.require(__requires__)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require\n    needed = self.resolve(parse_requirements(requirements))\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve\n    raise VersionConflict(dist, req).with_context(dependent_req)\npkg_resources.ContextualVersionConflict: (pyaaf2 1.4.0 (/home/karthik/venv3/lib/python3.6/site-packages), Requirement.parse(\'pyaaf2==1.2.0\'), {\'OpenTimelineIO\'})\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/karthik/venv3/bin/otiocat", line 6, in <module>\n    from pkg_resources import load_entry_point\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>\n    @_call_aside\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside\n    f(*args, **kwargs)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master\n    return cls._build_from_requirements(__requires__)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements\n    dists = ws.resolve(reqs, Environment())\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound: The \'pyaaf2==1.2.0\' distribution was not found and is required by OpenTimelineIO\n'

======================================================================
FAIL: test_input_argument_error (test_console.CreateShelloutTest.<locals>.newSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 281, in test_input_argument_error
    self.assertIn('error: input adapter', sys.stderr.getvalue())
AssertionError: 'error: input adapter' not found in 'Traceback (most recent call last):\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master\n    ws.require(__requires__)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require\n    needed = self.resolve(parse_requirements(requirements))\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve\n    raise VersionConflict(dist, req).with_context(dependent_req)\npkg_resources.ContextualVersionConflict: (pyaaf2 1.4.0 (/home/karthik/venv3/lib/python3.6/site-packages), Requirement.parse(\'pyaaf2==1.2.0\'), {\'OpenTimelineIO\'})\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/karthik/venv3/bin/otioconvert", line 6, in <module>\n    from pkg_resources import load_entry_point\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>\n    @_call_aside\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside\n    f(*args, **kwargs)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master\n    return cls._build_from_requirements(__requires__)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements\n    dists = ws.resolve(reqs, Environment())\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound: The \'pyaaf2==1.2.0\' distribution was not found and is required by OpenTimelineIO\n'

======================================================================
FAIL: test_media_linker_argument_error (test_console.CreateShelloutTest.<locals>.newSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 327, in test_media_linker_argument_error
    self.assertIn('error: media linker', sys.stderr.getvalue())
AssertionError: 'error: media linker' not found in 'Traceback (most recent call last):\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master\n    ws.require(__requires__)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require\n    needed = self.resolve(parse_requirements(requirements))\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve\n    raise VersionConflict(dist, req).with_context(dependent_req)\npkg_resources.ContextualVersionConflict: (pyaaf2 1.4.0 (/home/karthik/venv3/lib/python3.6/site-packages), Requirement.parse(\'pyaaf2==1.2.0\'), {\'OpenTimelineIO\'})\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/karthik/venv3/bin/otioconvert", line 6, in <module>\n    from pkg_resources import load_entry_point\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>\n    @_call_aside\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside\n    f(*args, **kwargs)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master\n    return cls._build_from_requirements(__requires__)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements\n    dists = ws.resolve(reqs, Environment())\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound: The \'pyaaf2==1.2.0\' distribution was not found and is required by OpenTimelineIO\n'

======================================================================
FAIL: test_output_argument_error (test_console.CreateShelloutTest.<locals>.newSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karthik/meshula/OpenTimelineIO/tests/test_console.py", line 303, in test_output_argument_error
    self.assertIn('error: output adapter', sys.stderr.getvalue())
AssertionError: 'error: output adapter' not found in 'Traceback (most recent call last):\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master\n    ws.require(__requires__)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require\n    needed = self.resolve(parse_requirements(requirements))\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve\n    raise VersionConflict(dist, req).with_context(dependent_req)\npkg_resources.ContextualVersionConflict: (pyaaf2 1.4.0 (/home/karthik/venv3/lib/python3.6/site-packages), Requirement.parse(\'pyaaf2==1.2.0\'), {\'OpenTimelineIO\'})\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/karthik/venv3/bin/otioconvert", line 6, in <module>\n    from pkg_resources import load_entry_point\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>\n    @_call_aside\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside\n    f(*args, **kwargs)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master\n    return cls._build_from_requirements(__requires__)\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements\n    dists = ws.resolve(reqs, Environment())\n  File "/home/karthik/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound: The \'pyaaf2==1.2.0\' distribution was not found and is required by OpenTimelineIO\n'

----------------------------------------------------------------------
Ran 356 tests in 3.006s

FAILED (failures=5, errors=5)
Makefile:40: recipe for target 'test-core' failed
make: *** [test-core] Error 1

```

**Comment by meshula** [comment]
1. There are a number of other things that need to be addressed before we separate the projects, for example, OTIO needs to publish a cmake config file. I've got that PR underway.

2a. The Python tests may have failed due to a change I made for rpaths that might not be linux compatible. I have a new version in the PR I made to the main repo, I'll sort the issues out there.

2b. The tests can be run from the command line, they'll appear in their respective build directories. I didn't check how make test is set up (since I don't use make often), I'll test that as well on the main repo.

3. I'm closing this, and after I've got the cmake issues sorted out, I'll open a PR that doesn't mix cmake and C tweaks!

**Comment by KarthikRIyer** [comment]
Earlier I didn't have to setup `make test`. After enabling testing in the cmake file and adding the tests it just worked. It worked with IDEs too. (I used CLion)

In the main repo a makefile is already there with the `make test` target defined, which runs the python tests. So running `make test` from the terminal just ran the python tests for me.

**Comment by meshula** [comment]
Yes, for sure that's true. The makefile runs the command ```python -m unittest discover -s tests -v``` and when the new Cmake files are committed, that will again work properly.

**Pull request closed without merging**
